问题：我们在数据库操作的时候，比如 dao 层中当遇到一个 sql.ErrNoRows 的时候，
     是否应该 Wrap 这个 error，抛给上层。为什么，应该怎么做请写出代码？

答：这个错误当然需要处理，并抛给调用方。实际上，我们经常需要在error返回给调用方之前加上一些额外的信息，
   帮助调用方定位error来自哪里、产生error的原因等。这是就可以用到github.com/pkg/errors包的wrap函数。
   示例代码如下：

package main

import (
   "database/sql"
   "fmt"

   "github.com/pkg/errors"
)

func foo() error {
   return errors.Wrap(sql.ErrNoRows, "foo failed")
}

func bar() error {
   return errors.WithMessage(foo(), "bar failed")
}

func main() {
   err := bar()
   if errors.Cause(err) == sql.ErrNoRows {
      fmt.Printf("data not found, %v\n", err)
      fmt.Printf("%+v\n", err)
      return
   }
   if err != nil {
      // unknown error
   }
}